### ISSUE TITLE
Document how to install the plugin

### ISSUE THREAD

**Issue by ddbaron** [ibmjstart/wp-bluemix-objectstorage#2]
Currently the documentation indicates the plugin is 'integrated into the buildpack'. If it's possible, please describe how to install this plugin in the event you are not using the provided buildpack. In my case, I've used the manual install instructions but would still like to benefit from this plugin.

**Comment by bradjones1** [comment]
Specifically, this plugin expects VCAP environment variables, however if you're not using this plugin in the context of a Bluemix-initiated service, you must set them manually.

See https://console.ng.bluemix.net/docs/cli/vcapsvc.html

**Comment by lmsurpre** [comment]
Use of this plugin outside of the wordpress on bluemix project is not well-tested and, while we think it should work, we'd prefer not to encourage it at this time.  Feel free to re-open if you can't get it to work.

**Comment by bradjones1** [comment]
@lmsurpre That's your prerogative, of course, but as a Softlayer customer I don't really see why IBM wouldn't want to encourage the use of this in the corporate ecosystem. For cost, control and other reasons I maintain my own private cloud of sorts using a combination of VMs and bare metal servers, and I make increasing use of Bluemix Object Storage for those services. I'd hate to see this project forked simply because a few environment variables would get set in a different way?
